
export interface Scenario {
  id: number;
  text: string;
}

export const scenarios: Scenario[] = [
  // Original scenarios
  { id: 1, text: "... hat keinen Führerschein" },
  { id: 2, text: "... steht auf Füße" },
  { id: 3, text: "... redet mit Pflanzen" },
  { id: 4, text: "... hat denselben Vornamen wie dein Ex" },
  { id: 5, text: "... besteht auf tägliches Horoskop-Lesen vor Entscheidungen" },
  { id: 6, text: "... trägt immer Tierkostüme zu Hause" },
  { id: 7, text: "... glaubt an Verschwörungstheorien" },
  { id: 8, text: "... hat noch nie eine Serie durchgeschaut" },
  { id: 9, text: "... telefoniert jeden Tag eine Stunde mit den Eltern" },
  { id: 10, text: "... lässt den Wasserhahn beim Zähneputzen laufen" },
  { id: 11, text: "... ist ein verurteilter Steuerhinterzieher" },
  { id: 12, text: "... hängt täglich 5 Stunden auf Social Media" },
  { id: 13, text: "... ist Vegetarier/in und kritisiert jeden, der Fleisch isst" },
  { id: 14, text: "... schläft immer mit 5 großen Kuscheltieren im Bett" },
  { id: 15, text: "... lacht grundsätzlich über die eigenen Witze" },
  { id: 16, text: "... sammelt lebende Spinnen als Haustiere" },
  { id: 17, text: "... hat eine Kollektion von über 200 Paar Schuhen" },
  { id: 18, text: "... will mindestens 8 Kinder haben" },
  { id: 19, text: "... geht nie ohne volle Kriegsbemalung aus dem Haus" },
  { id: 20, text: "... singt ständig Disney-Lieder beim Duschen" },
  { id: 21, text: "... ist noch Jungfrau mit 35" },
  { id: 22, text: "... sortiert Gummibärchen nach Farben, bevor sie gegessen werden" },
  { id: 23, text: "... führt Selbstgespräche in der dritten Person" },
  { id: 24, text: "... kann nur einschlafen, wenn der Fernseher läuft" },
  { id: 25, text: "... trägt grundsätzlich nur Kleidung von einer bestimmten Marke" },
  { id: 26, text: "... postet jede Mahlzeit auf Instagram" },
  { id: 27, text: "... liest Zeitungen von hinten nach vorne" },
  { id: 28, text: "... hat ein lebensgroßes Poster eines Prominenten im Schlafzimmer" },
  { id: 29, text: "... hat eine Allergie gegen Haustiere" },
  { id: 30, text: "... beendet Unterhaltungen immer mit einem Fingerschnipsen" },
  { id: 31, text: "... trägt auch im Winter Sandalen mit Socken" },
  { id: 32, text: "... besteht darauf, dass beide Partner denselben Haarschnitt tragen" },
  { id: 33, text: "... hat einen schrecklichen Musikgeschmack" },
  { id: 34, text: "... hat 7 gescheiterte Ehen hinter sich" },
  { id: 35, text: "... teilt ein Bankkonto mit den Eltern" },
  { id: 36, text: "... weigert sich, Trinkgeld zu geben" },
  { id: 37, text: "... sammelt Fingernägelabschnitte in einem Glas" },
  { id: 38, text: "... spricht mit einem übertriebenen britischen Akzent, obwohl nicht von dort" },
  { id: 39, text: "... hat ein Tattoo des Ex-Partners, das nicht entfernt werden soll" },
  { id: 40, text: "... begrüßt jeden mit einem komplizierten Handshake-Ritual" },
  
  // New scenarios (mixed in randomly)
  { id: 41, text: "... liebt Analsex – und redet sofort drüber" },
  { id: 42, text: "... isst mit offenem Mund und schmatzt laut" },
  { id: 43, text: "... macht beim Sex immer das Licht aus" },
  { id: 44, text: "... hat ein Tattoo mit dem Namen der Ex" },
  { id: 45, text: "... wohnt noch bei den Eltern – mit 34" },
  { id: 46, text: "... redet ständig von „der Seelenverbindung"" },
  { id: 47, text: "... hat noch nie einen Orgasmus gehabt" },
  { id: 48, text: "... schreibt durchgehend in Großbuchstaben" },
  { id: 49, text: "... glaubt, dass Horoskope 100 % stimmen" },
  { id: 50, text: "... hat nur Freunde des anderen Geschlechts" },
  { id: 51, text: "... hört beim Einschlafen True-Crime-Podcasts" },
  { id: 52, text: "... hat Sex nur mit Socken an" },
  { id: 53, text: "... geht nie zum Zahnarzt – aus Prinzip" },
  { id: 54, text: "... ist gegen jegliche Körperbehaarung – auch bei dir" },
  { id: 55, text: "... besteht auf getrennte Schlafzimmer" },
  { id: 56, text: "... küsst seinen Hund auf den Mund" },
  { id: 57, text: "... trägt immer Jogginghose – auch beim Date" },
  { id: 58, text: "... hat eine sehr laute Stimme – überall" },
  { id: 59, text: "... lässt dich nie ans Steuer" },
  { id: 60, text: "... muss beim Sex immer Musik laufen lassen" },
  { id: 61, text: "... ist noch mit der/m Ex befreundet – sehr eng" },
  { id: 62, text: "... macht alles nach Plan – auch Dates" },
  { id: 63, text: "... ist noch Jungfrau – mit über 30" },
  { id: 64, text: "... geht nie ohne Mama-Essen aus dem Haus" },
  { id: 65, text: "... hatte über 50 Sexualpartner" },
  { id: 66, text: "... schreibt ständig mit dem Handy während Gesprächen" },
  { id: 67, text: "... weint bei fast jedem Film" },
  { id: 68, text: "... hat noch nie einen Orgasmus bei Partnersex erlebt" },
  { id: 69, text: "... will sofort zusammenziehen" },
  { id: 70, text: "... besteht auf getrennte Urlaube" },
  { id: 71, text: "... duscht nur alle 3 Tage" },
  { id: 72, text: "... hört nur Schlager – auch beim Sex" },
  { id: 73, text: "... fragt beim ersten Date nach Kinderwunsch" },
  { id: 74, text: "... liebt Rollenspiele – auch im Alltag" },
  { id: 75, text: "... schläft mit einem Kuscheltier – immer" },
  { id: 76, text: "... hat eine spezielle Vorliebe für Achselgeruch" },
  { id: 77, text: "... ist sehr eifersüchtig – auch bei Insta-Likes" },
  { id: 78, text: "... ruft dich nach dem ersten Date sofort „Baby"" },
  { id: 79, text: "... möchte unbedingt eine offene Beziehung" },
  { id: 80, text: "... hat einen Fetisch für High Heels" },
  { id: 81, text: "... fragt beim zweiten Treffen nach einem Dreier" },
  { id: 82, text: "... hält Händchen selbst beim Zähneputzen" },
  { id: 83, text: "... redet beim Sex sehr viel" },
  { id: 84, text: "... glaubt, dass Monogamie unnatürlich ist" },
  { id: 85, text: "... trinkt keinen Alkohol – gar nicht" },
  { id: 86, text: "... will Sex nur in Missionarsstellung" },
  { id: 87, text: "... hat extrem lange Fingernägel – auch als Mann" },
  { id: 88, text: "... hat Sex nur nach dem Duschen – immer" },
  { id: 89, text: "... hat noch nie gevögelt – weil „es nie gepasst hat"" },
  { id: 90, text: "... macht beim Orgasmus Tiergeräusche" },
  { id: 91, text: "... hat noch nie Sport gemacht" },
  { id: 92, text: "... schläft mit offener Tür – auch bei Besuch" },
  { id: 93, text: "... will beim Sex gefesselt werden" },
  { id: 94, text: "... will DICH beim Sex fesseln" },
  { id: 95, text: "... redet beim ersten Date nur über Ex-Partner" },
  { id: 96, text: "... hat ein Tattoo im Intimbereich mit einem Namen" },
  { id: 97, text: "... hat Sex nach Plan – immer dienstags und freitags" },
  { id: 98, text: "... teilt ständig Zitate von „Coachings" auf Instagram" },
  { id: 99, text: "... möchte keinen Oralsex – weder geben noch bekommen" },
  { id: 100, text: "... ist absolut gegen Selbstbefriedigung" },
  { id: 101, text: "... besteht auf gemeinsames Duschen – immer" },
  { id: 102, text: "... lässt Körpergerüche bewusst „natürlich"" },
  { id: 103, text: "... lacht beim Sex" },
  { id: 104, text: "... wurde noch nie geküsst" },
  { id: 105, text: "... glaubt, dass Sex vor der Ehe falsch ist" },
  { id: 106, text: "... sagt beim Orgasmus deinen Namen – auch wenn du ihn falsch gesagt hast" },
  { id: 107, text: "... mag keine Tiere – überhaupt nicht" },
  { id: 108, text: "... hat ständig eine Kamera dabei – auch beim Frühstück" },
  { id: 109, text: "... will, dass du deine Socials löscht, wenn ihr zusammenkommt" },
  { id: 110, text: "... hat eine Dating-History voller Drama" },
  { id: 111, text: "... besteht auf „30-Tage-Zölibat" vorm Sex" },
  { id: 112, text: "... fragt ständig nach Bestätigung („Magst du mich WIRKLICH?")" },
  { id: 113, text: "... will Sex nur mit Licht an" },
  { id: 114, text: "... geht nie ans Handy – auch bei Notfällen" },
  { id: 115, text: "... steht auf Dirty Talk – auf Hochdeutsch" },
  { id: 116, text: "... will beim Sex beleidigt werden" },
  { id: 117, text: "... ist stolz darauf, ein „Herzensbrecher" zu sein" },
  { id: 118, text: "... ruft täglich 5x an, um zu „hören, wie's dir geht"" },
  { id: 119, text: "... isst nur Babybrei" },
  { id: 120, text: "... schickt nach jedem Date eine ausführliche Feedback-Sprachnachricht" },
  { id: 121, text: "... besteht auf getrennte Konten ab dem ersten Monat" },
  { id: 122, text: "... glaubt, Kondome seien unnatürlich" },
  { id: 123, text: "... hat extreme Angst vor Körperflüssigkeiten" },
  { id: 124, text: "... ist bei Mama auf Platz 1 – du auf Platz 2" },
  { id: 125, text: "... schaut jeden Abend Disney-Filme zum Einschlafen" },
  { id: 126, text: "... hat im Schlafzimmer Schwarzlicht installiert" },
  { id: 127, text: "... sagt dir beim ersten Date den Vornamen der zukünftigen Kinder" },
  { id: 128, text: "... möchte, dass du dich vollständig rasierst – überall" },
  { id: 129, text: "... fragt beim Kennenlernen nach deinem Gehalt" },
  { id: 130, text: "... sagt beim Sex religiöse Sätze („Oh Herr!")" },
  { id: 131, text: "... gibt deinem Geschlechtsteil einen eigenen Namen" },
  { id: 132, text: "... besteht auf veganem Sexspielzeug" },
  { id: 133, text: "... hat über 100 Selfies pro Tag auf dem Handy" },
  { id: 134, text: "... will dich in die Familie aufnehmen – sofort" },
  { id: 135, text: "... hält Sex für „überbewertet"" },
  { id: 136, text: "... möchte nur Sex mit Musik von Helene Fischer" },
  { id: 137, text: "... besteht auf täglichem Beziehungstagebuch" },
  { id: 138, text: "... hat ein Kuschelbedürfnis von 5+ Stunden täglich" },
  { id: 139, text: "... besteht darauf, dass du seine/ihre Füße massierst" },
  { id: 140, text: "... hat beim Sex immer einen Spiegel dabei" },
  { id: 141, text: "... trägt nie Unterwäsche" },
  { id: 142, text: "... hört beim Sex Podcasts" },
  { id: 143, text: "... nennt sich selbst „Alpha"" },
  { id: 144, text: "... isst gerne im Bett – auch warme Mahlzeiten" },
  { id: 145, text: "... glaubt, dass Männer keine Tränen zeigen dürfen" },
  { id: 146, text: "... besteht auf täglichem Paar-Yoga" },
  { id: 147, text: "... hat eine Dating-To-Do-Liste" },
  { id: 148, text: "... liebt es, beim Sex zu telefonieren" },
  { id: 149, text: "... hält Händchen beim Autofahren – immer" },
  { id: 150, text: "... macht jeden Tag 20 Selfies mit dir" },
  { id: 151, text: "... findet Körperbehaarung „eklig"" },
  { id: 152, text: "... besteht darauf, nie zu furzen – auch nicht im Schlaf" },
  { id: 153, text: "... möchte, dass du seine/ihre Unterwäsche wäschst" },
  { id: 154, text: "... schickt dir jeden Tag Guten-Morgen- UND Gute-Nacht-Videos" },
  { id: 155, text: "... fragt bei jedem Gespräch: „Vermisst du mich?"" },
  { id: 156, text: "... nutzt dein Parfüm heimlich" },
  { id: 157, text: "... hat dich nach 2 Dates den Eltern vorgestellt" },
  { id: 158, text: "... will, dass du beim Sex immer ein Kostüm trägst" },
  { id: 159, text: "... besteht darauf, dass Sex nur in einem bestimmten Raum stattfinden darf" },
  { id: 160, text: "... schreibt in Babysprache" },
  { id: 161, text: "... hat eine spezielle Playlist für Orgasmen" },
  { id: 162, text: "... isst rohe Zwiebeln wie Äpfel" },
  { id: 163, text: "... sagt beim Sex Zitate aus Filmen" },
  { id: 164, text: "... hat deine Nachrichten mit Emojis kommentiert – einzeln" },
  { id: 165, text: "... besteht auf 100 % veganer Beziehung (inkl. Kosmetik, Kleidung)" },
  { id: 166, text: "... will beim Sex unbedingt Augenkontakt – dauerhaft" },
  { id: 167, text: "... will dich beim Sex mit deinem Ex-Namen anreden" },
  { id: 168, text: "... hört seine eigene Stimme in Loops beim Einschlafen" },
  { id: 169, text: "... mag keine Berührungen" },
  { id: 170, text: "... macht alle 5 Minuten Selfies beim Date" },
  { id: 171, text: "... besteht auf täglichem Beziehungsbericht per Mail" },
  { id: 172, text: "... hat keine Freunde – aus Prinzip" },
  { id: 173, text: "... hat noch nie „Ich liebe dich" gesagt" },
  { id: 174, text: "... hält sich für einen Gott im Bett" },
  { id: 175, text: "... schickt dir Nacktbilder, ohne zu fragen" },
  { id: 176, text: "... besteht auf astrologisch kompatible Sternzeichen" },
  { id: 177, text: "... hat einen Fetisch für Ohren" },
  { id: 178, text: "... nennt dich bei jedem Namen außer deinem eigenen" },
  { id: 179, text: "... besteht auf intellektuelle Diskussionen – auch beim Vorspiel" },
  { id: 180, text: "... trinkt nur Smoothies – auch beim Dinner-Date" },
  { id: 181, text: "... glaubt, dass Sex nur zur Fortpflanzung da ist" },
  { id: 182, text: "... will bei jedem Treffen nackt sein" },
  { id: 183, text: "... hört beim Sex Heavy Metal" },
  { id: 184, text: "... hat eine Beziehung zu einer Sexpuppe" },
  { id: 185, text: "... besteht auf gemeinsames Tagebuchschreiben nach dem Sex" },
  { id: 186, text: "... möchte beim Date dein Handy checken" },
  { id: 187, text: "... redet mit sich selbst – im Dialog" },
  { id: 188, text: "... glaubt, Sex ist „Energieaustausch" mit kosmischer Bedeutung" },
  { id: 189, text: "... gibt kein Trinkgeld – nie" },
  { id: 190, text: "... ist unhöflich zu Kellnern" },
  { id: 191, text: "... redet mehr über sich als über dich" },
  { id: 192, text: "... kommt 30 Minuten zu spät – ohne Bescheid zu sagen" },
  { id: 193, text: "... lässt dich zahlen, obwohl er/sie eingeladen hat" },
  { id: 194, text: "... redet beim ersten Date schon von „für immer"" },
  { id: 195, text: "... kaut laut mit offenem Mund" },
  { id: 196, text: "... schaut ständig aufs Handy" },
  { id: 197, text: "... hat einen starken Körpergeruch" },
  { id: 198, text: "... hat dreckige Fingernägel" },
  { id: 199, text: "... unterbricht dich bei jedem Satz" },
  { id: 200, text: "... trägt einen Jogginganzug zum Date" },
  { id: 201, text: "... schnipst nach dem Servicepersonal" },
  { id: 202, text: "... erzählt ungefragt von Schulden" },
  { id: 203, text: "... lutscht die Finger beim Essen ab" },
  { id: 204, text: "... macht respektlose Witze über Ex-Partner" },
  { id: 205, text: "... stellt intime Fragen beim ersten Treffen" },
  { id: 206, text: "... fragt direkt nach deinem Kontostand" },
  { id: 207, text: "... spricht extrem abwertend über andere Menschen" },
  { id: 208, text: "... bringt ungefragt jemanden zum Date mit" },
  { id: 209, text: "... nimmt das Handy beim Gespräch auf – ohne Entschuldigung" },
  { id: 210, text: "... kommt total verschwitzt und ungepflegt" },
  { id: 211, text: "... pustet sich beim Essen die Nase – ohne Taschentuch" },
  { id: 212, text: "... spricht nur von sich selbst in der dritten Person" },
  { id: 213, text: "... macht ständig Selfies während des Dates" },
  { id: 214, text: "... rülpst laut – mehrfach" },
  { id: 215, text: "... lässt dich nicht ausreden" },
  { id: 216, text: "... macht sich über dein Aussehen lustig" },
  { id: 217, text: "... spielt beim Date mit seinen Zehennägeln" },
  { id: 218, text: "... kaut Kaugummi wie ein Teenie" },
  { id: 219, text: "... macht politische Witze – und meint sie ernst" },
  { id: 220, text: "... redet nur von Geld und Autos" },
  { id: 221, text: "... lässt dich im Regen stehen – buchstäblich" },
  { id: 222, text: "... sagt beim ersten Date: „Ich bin nicht wie die anderen"" },
  { id: 223, text: "... hat beim Treffen dreckige Kleidung an" },
  { id: 224, text: "... trägt zu viel Parfüm – erstickend" },
  { id: 225, text: "... trägt Sonnenbrille – auch drinnen, auch abends" },
  { id: 226, text: "... sagt Sätze wie „Ich bin einfach ehrlich – manche halten das nicht aus"" },
  { id: 227, text: "... macht ständig TikTok-Videos – auch vom Essen" },
  { id: 228, text: "... lässt dich nicht zu Wort kommen" },
  { id: 229, text: "... hat keine Tischmanieren" },
  { id: 230, text: "... leckt den Teller ab" },
  { id: 231, text: "... kommt mit leerem Portemonnaie und sagt „Ich hab's vergessen"" },
  { id: 232, text: "... meckert über alles – das Wetter, das Essen, die Bedienung" },
  { id: 233, text: "... wippt nervös mit dem Bein die ganze Zeit" },
  { id: 234, text: "... rollt ständig mit den Augen" },
  { id: 235, text: "... lässt dich beim Gespräch durch die Gegend laufen, um Leute zu grüßen" },
  { id: 236, text: "... ruft mitten im Gespräch jemanden an und redet minutenlang" },
  { id: 237, text: "... kommentiert ständig dein Aussehen" },
  { id: 238, text: "... sagt, dass alle Exen „psychisch krank" waren" },
  { id: 239, text: "... wohnt in einer WG mit 6 Personen – alle zwischen 18 und 19" },
  { id: 240, text: "... hat keine Hobbys – wirklich keine" },
  { id: 241, text: "... steht jeden Tag um 5 Uhr auf – und erwartet das auch von dir" },
  { id: 242, text: "... zieht nie um – wohnt noch in seinem/ihrem Kinderzimmer" },
  { id: 243, text: "... hat noch nie selbst gekocht" },
  { id: 244, text: "... sagt „Arbeit ist nur was für Dumme"" },
  { id: 245, text: "... macht nie Urlaub – „ist rausgeschmissenes Geld"" },
  { id: 246, text: "... isst nur Tiefkühlpizza – täglich" },
  { id: 247, text: "... trinkt 5 Energydrinks am Tag" },
  { id: 248, text: "... hört bei jedem Gespräch Podcast – mit einem AirPod im Ohr" },
  { id: 249, text: "... lebt aus einem Koffer – freiwillig" },
  { id: 250, text: "... hat keinen Plan für die Zukunft – „lass einfach treiben"" },
  { id: 251, text: "... hat 9 Jobs in 2 Jahren gehabt" },
  { id: 252, text: "... ist 30+ und hat noch nie Wäsche selbst gewaschen" },
  { id: 253, text: "... trägt immer denselben Pullover – auch im Sommer" },
  { id: 254, text: "... redet ständig davon, auszuwandern – aber tut es nie" },
  { id: 255, text: "... hat keinen Schulabschluss – und keine Pläne" },
  { id: 256, text: "... braucht täglich „mindestens 3 Stunden Me-Time"" },
  { id: 257, text: "... hat jedes Hobby nach 2 Wochen wieder aufgegeben" },
  { id: 258, text: "... hängt täglich 8 Stunden auf Reddit" },
  { id: 259, text: "... muss alles kontrollieren – auch wie du deinen Kaffee trinkst" },
  { id: 260, text: "... hasst Tiere – ALLE" },
  { id: 261, text: "... geht nie raus – „ich hasse Menschen"" },
  { id: 262, text: "... redet von sich als „einsamer Wolf"" },
  { id: 263, text: "... hat kein Problem damit, 4 Tage dieselben Klamotten zu tragen" },
  { id: 264, text: "... hat keinen Müll getrennt – jemals" },
  { id: 265, text: "... gibt mit Markenklamotten an – lebt aber noch bei Mama" },
  { id: 266, text: "... macht in jeder freien Minute Gym – „alles andere ist Zeitverschwendung"" },
  { id: 267, text: "... schreibt Tagebuch – öffentlich auf Instagram" },
  { id: 268, text: "... hat einen Kalender mit „Mondphasen vs. Stimmung"" },
  { id: 269, text: "... geht nur raus, wenn es „energetisch gut steht"" },
  { id: 270, text: "... hört nur ein Lied – in Dauerschleife" },
  { id: 271, text: "... fährt überall mit dem E-Scooter hin – auch zum ersten Date" },
  { id: 272, text: "... isst nie mit Besteck" },
  { id: 273, text: "... besteht auf täglichem Meditieren in absoluter Stille" },
  { id: 274, text: "... will, dass du bei jedem Hobby mitziehst – sonst ist's „nicht kompatibel"" },
  { id: 275, text: "... reagiert passiv-aggressiv, wenn du „nein" sagst" },
  { id: 276, text: "... fragt ständig: „Wie findest du das, was ich gerade gesagt habe?"" },
  { id: 277, text: "... ist überfreundlich – aber zu allen, nicht nur zu dir" },
  { id: 278, text: "... redet bei jedem Smalltalk von spirituellen Energien" },
  { id: 279, text: "... nutzt Esoterik als Erklärung für alles" },
  { id: 280, text: "... macht alles „intuitiv" – auch Steuererklärung" },
  { id: 281, text: "... hat Angst vor Mikrowellen" },
  { id: 282, text: "... lebt minimalistisch – hat nur 5 Gegenstände in der Wohnung" },
  { id: 283, text: "... ist süchtig nach Esports – auch während des Dates" },
  { id: 284, text: "... plant jede Minute des Tages – auch dein Leben gleich mit" },
  { id: 285, text: "... macht ständig Challenges (No Sugar, No Internet, No Spaß)" },
  { id: 286, text: "... möchte, dass du mit ihm/ihr in einen Tiny House ziehst – ohne Toilette" },
  { id: 287, text: "... hat alle Möbel auf dem Boden – „mehr Erdung"" },
  { id: 288, text: "... lässt nie Besuch zu Hause zu – „Energie bleibt sonst"" }
];

// Function to get random scenarios
export function getRandomScenarios(count: number = 10): Scenario[] {
  const shuffled = [...scenarios].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}
